x-airflow-common:
  &airflow-common
  image: apache/airflow:2.11.0
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${AIRFLOW_POSTGRES_DB}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    AIRFLOW__WEBSERVER__WEB_SERVER_PORT: ${AIRFLOW_WEBSERVER_PORT}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__FERNET_KEY}
    AIRFLOW__METRICS__TIMER_UNIT_CONSISTENCY: 'true'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
    AIRFLOW__CORE__DEFAULT_TIMEZONE: ${TZ}
    TZ: ${TZ}
  volumes:
    # - /var/run/docker.sock:/var/run/docker.sock       # required for docker exec
    # - /usr/bin/docker:/usr/bin/docker
    - ${AIRFLOW_PROJ_DIR}/dags:/opt/airflow/dags
    - ${AIRFLOW_PROJ_DIR}/config:/opt/airflow/config
    - ${AIRFLOW_PROJ_DIR}/plugins:/opt/airflow/plugins
    - ${AIRFLOW_PROJ_DIR}/logs:/opt/airflow/logs
    - ./data/raw:/opt/airflow/data                      # mount raw data directory
    # - ./scripts:/opt/airflow/scripts                  # mount scripts directory
    # - ${BACKUP_DIR}:/opt/airflow/${BACKUP_DIR}
    - ./.env:/opt/airflow/.env:ro

  user: "${AIRFLOW_UID}:0"
  group_add:
    - "984"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      AIRFLOW_POSTGRES_DB: ${AIRFLOW_POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ}
      PGTZ: ${TZ}
      PGPORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 10

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |

        # Initialize the database
        airflow db migrate

        # Check if postgres_connection connection exists, if not create it
        if ! airflow connections get postgres_connection >/dev/null 2>&1; then
          airflow connections add postgres_connection \
            --conn-type postgres \
            --conn-host postgres \
            --conn-login ${POSTGRES_USER} \
            --conn-password ${POSTGRES_PASSWORD} \
            --conn-schema ${POSTGRES_DB} \
            --conn-port ${POSTGRES_PORT}
          echo "Created postgres_connection connection"
        else
          echo "postgres_connection connection already exists, skipping creation"
        fi

        # Start Airflow version check
        exec /entrypoint airflow version
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD}
    user: "0:0"
    # volumes:
    #   # - /usr/bin/docker:/usr/bin/docker
    #   - ${AIRFLOW_PROJ_DIR}/dags:/sources/dags
    #   - ${AIRFLOW_PROJ_DIR}/plugins:/sources/plugins
    #   - ${AIRFLOW_PROJ_DIR}/logs:/sources/logs
    #   - ./scripts:/opt/airflow/scripts
    #   - ${BACKUP_DIR}:/opt/airflow/${BACKUP_DIR}
    #   - ./.env:/opt/airflow/.env:ro
    #   - ${BULK_SCRAPE_DATA_DIR}:/opt/airflow/bulk_scrape:ro
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: >
      bash -c "exec airflow scheduler"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8974/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: >
      bash -c "exec airflow webserver"
    ports:
      - ${AIRFLOW_WEBSERVER_PORT}:${AIRFLOW_WEBSERVER_PORT}
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:${AIRFLOW_WEBSERVER_PORT}/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

networks:
  default:
    name: ${DOCKER_NETWORK}
